eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
      - id: usuarios
        uri: http://localhost:8081
        predicates:
        - Path=/api/v1/usuarios
      - id: tareas
        uri: http://localhost:8082
        predicates:
        - Path=/api/v1/tareas/**
      - id: discovery-server
        filters:
        - SetPath=/
        uri: http://localhost:8761
        predicates:
        - Path=/eureka/web
      - id: discovery-server-static
        uri: http://localhost:8761
        predicates:
        - Path=/eureka/**

management:
  endpoints:
    web:
      exposure:
        include: "*"
